version: '3.7'

services:
  db:
    image: postgres:12.3-alpine
    container_name: bam-db-dev
    restart: unless-stopped
    volumes:
      - ./.docker/data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: db